plugins {
    id 'java'
    id 'java-test-fixtures'
}

group = 'com.github.mehrunessky.demo.blog'
version = '1.0-SNAPSHOT'


dependencies {
    compileOnly("org.projectlombok:lombok:1.18.42")
    annotationProcessor("org.projectlombok:lombok:1.18.42")

    testCompileOnly("org.projectlombok:lombok:1.18.42")
    testAnnotationProcessor("org.projectlombok:lombok:1.18.42")

    testFixturesCompileOnly("org.projectlombok:lombok:1.18.42")
    testFixturesAnnotationProcessor("org.projectlombok:lombok:1.18.42")
}

repositories {
    mavenCentral()
}