name: Publish files to Gist

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "mother/src/testFixtures/java/com/github/mehrunessky/demo/blog/mother/PersonMother.java"
      - "mother/build.gradle"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Publish to Gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: 7dbb4bb4742a858061b947ba4dc220d1
          file_path: |
            mother/src/testFixtures/java/com/github/mehrunessky/demo/blog/mother/PersonMother.java
            mother/build.gradle