name: Publish files to Gist

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "mother/src/testFixtures/java/com/github/mehrunessky/demo/blog/mother/PersonMother.java"
      - "mother/build.gradle"

env:
  GIST_FILES: |
    mother/src/testFixtures/java/com/github/mehrunessky/demo/blog/mother/PersonMother.java
    mother/build.gradle

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Publish files to Gist
        run: |
          for file in $GIST_FILES; do
            name=$(echo "$file" | tr '/' '_')
            echo "Publishing $file $name"
            gh gist edit 7dbb4bb4742a858061b947ba4dc220d1 \
              --filename "$name" \
              --add "$file"
          done
        env:
          GH_TOKEN: ${{ secrets.GIST_TOKEN }}